# Generated by Django 2.2.5 on 2019-09-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=128, unique=True)),
                ('u_password', models.CharField(default='a12345678', max_length=128)),
                ('u_last_time', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'auto_user',
            },
        ),
    ]
